### ISSUE TITLE
auto-select

### ISSUE THREAD

**Issue by anticapitalista** [AdrianTM/mx-repo-manager#3]
I got this feedback from an antiX user.

Upon selecting some repository and confirming it, the one at the very bottom gets auto-selected.
If it's impossible to make it stay at the chosen repository, then it should 'auto-jump' to the default repository and not to the last on the list (which is Vietnam).
If it's impossible to make it jump to default, maybe it'd be possible to place the default repository at the very end of the list, so it jumps to the bottom like right now, but not auto-selecting Vietnam.

It might be only nitpicking when it comes to functionality itself, but such details are pretty important from the "user experience" point of view.

**Comment by AdrianTM** [comment]
Can't confirm, works OK here. not sure what version antiX uses and if there's a difference in how repos are listed.

**Comment by anticapitalista** [comment]
Yes, you are right. It works ok on MX. I'll check antiX version

**Comment by anticapitalista** [comment]
Strange - made new changes (on antiX) - still defaults to last (Vietnam).
Installed mx-repo-manager and mx-repo-list on antiX and get the same ie defaults to last (Vietnam).
Am I missing a lib on antiX?

**Comment by AdrianTM** [comment]
See what command is run if it looks OK, it should show the commands in CLI, for MX it shows something like ""set -o pipefail; netselect -D -I https://mirrors.evowise.com/mxlinux-packages http://mxlinux.unc.edu.ar/mxlinux http://mirror.launtel.net.au/repo/mx http://mx.mirror.ausnetservers.net.au/packages http://mirror.datamossa.io/mxlinux http://debian.mur.at/mx-linux http://mirror.digitalnova.at/mxlinux/packages http://mirror.easyname.at/mxlinux-packages http://mirror.datacenter.az/mxlinux https://mirror.datacenter.by/pub/mirrors/mxlinux.org/packages http://mirror.adct.be/mx/packages https://ftp.belnet.be/mirror2/ftp.belnet.be/mxlinux/packages http://mirror.retentionrange.co.bw/mxlinux/packages http://mirror.ufam.edu.br/mx https://mxlinux.c3sl.ufpr.br/mx-workspace ..."

**Comment by anticapitalista** [comment]
Running mx-repo-manager in a terminal shows:

mx-repo-manager 
"dpkg-query -f '${Version}' -W mx-repo-manager"
exit code: 0
"grep -m1 '^deb.*/repo/ ' /etc/apt/sources.list.d/mx.list | cut -d' ' -f2 | cut -d/ -f3"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/antix.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/debian-stable-updates.list"
"cat /etc/debian_version | cut -f1 -d'.'"
exit code: 0
"sed -i 's;deb.*/repo/ ;deb https://repo.cure.edu.uy/mxlinux/packages/mx/repo/ ;' /etc/apt/sources.list.d/mx.list && sed -i 's;deb.*/testrepo/ ;deb https://repo.cure.edu.uy/mxlinux/packages/mx/testrepo/ ;' /etc/apt/sources.list.d/mx.list"
exit code: 0
"sed -i 's;https\?://.*/stretch/\?;https://repo.cure.edu.uy/mxlinux/packages/antix/stretch/;' /etc/apt/sources.list.d/antix.list"
exit code: 0
"grep -m1 '^deb.*/repo/ ' /etc/apt/sources.list.d/mx.list | cut -d' ' -f2 | cut -d/ -f3"
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1294, resource id: 8400777, major code: 40 (TranslateCoords), minor code: 0
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/antix.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/debian-stable-updates.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/debian.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/mx.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/onion.list"
exit code: 0
"grep '^#*[ ]*deb' /etc/apt/sources.list.d/others.list"
exit code: 0

**Comment by AdrianTM** [comment]
I meant when you press "select fastest repo"

Also, I notice a lot of mx.list references there, you probably didn't adapt it to antiX specifics...
