### ISSUE TITLE
Would this run on Ubuntu? 

### ISSUE THREAD

**Issue by heelrayner** [AdrianTM/mx-repo-manager#4]

**Comment by AdrianTM** [comment]
No, nobody should run "MX" apps on Ubuntu, even if they "run" they are not tested and can break things. This is specifically a manager of MX repos, why would you run it on Ubuntu? 

That being said if somebody knows what they are doing and modifies the code they can use it however they want.

**Comment by heelrayner** [comment]
My only issue with running MX is that there's no chat, and I couldn't get
ffxi running on it.
