### ISSUE TITLE
Troublesome detail

### ISSUE THREAD

**Issue by serainox420** [AdrianTM/mx-repo-manager#7]
Hey, can you edit the program (or sources file) not to allow this:
If you try to checkmark `# debian backports` which clearly is a code comment, not supposed to be a checkable option... Will break APT and dpkg untill this very specific line is reverted or removed.
I checked 
I checked it by mistake once, doing a routine install and adding sources, then it messed up my package maanagement for few hours untill I realised what just happened.

Either add `debian backports` as a interface thing under which to show backports, or simply remove that comment from actual sources file.

I might not be a mission critical type of bug to fix, but If I got confused and something like that just confused the hell out of me as I was trying to think of all the sus things I've been doing to APT recently, and last to suspect is the tool that allows dumb people to get dumber :)

![Screenshot_2023-10-17_01-50-31](https://github.com/AdrianTM/mx-repo-manager/assets/95081005/84741198-f65a-4cb4-b54b-354e026e402a)

**Comment by AdrianTM** [comment]
This looks like a problem I already fixed (hopefully), moreover I cannot seem to replicate it. 

What version of the program are you running? If you run the current one can you send me the /etc/apt/source.list.d/debian.list file?
